name: Setup Bun Environment
description: Install Bun and repository dependencies

inputs:
  bun-version-file:
    description: Bun version file path
    required: false
    default: package.json
  args:
    description: Arguments passed to `bun install`
    required: false
    default: --frozen-lockfile

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ${{ inputs.bun-version-file }}

    - name: Install dependencies
      run: bun install ${{ inputs.args }}
      shell: bash
