import { mkdir } from 'node:fs/promises';
import path from 'node:path';

type JsonObject = Record<string, unknown>;

interface OpenApiDocument {
  info?: {
    title?: string;
    version?: string;
  };
  paths?: Record<string, PathItem>;
  components?: {
    schemas?: Record<string, SchemaObject>;
  };
}

type PathItem = Partial<Record<HttpMethod, OperationObject>>;
type HttpMethod =
  | 'get'
  | 'put'
  | 'post'
  | 'delete'
  | 'options'
  | 'head'
  | 'patch'
  | 'trace';

interface OperationObject {
  tags?: string[];
  summary?: string;
  description?: string;
  operationId?: string;
  parameters?: ParameterObject[];
  requestBody?: RequestBodyObject;
  responses?: Record<string, ResponseObject>;
}

interface ParameterObject {
  name?: string;
  in?: string;
  required?: boolean;
  description?: string;
  schema?: SchemaObject;
}

interface RequestBodyObject {
  required?: boolean;
  content?: Record<string, MediaTypeObject>;
}

interface MediaTypeObject {
  schema?: SchemaObject;
}

interface ResponseObject {
  description?: string;
  content?: Record<string, MediaTypeObject>;
}

interface SchemaObject {
  $ref?: string;
  type?: string;
  format?: string;
  enum?: unknown[];
  title?: string;
  description?: string;
  default?: unknown;
  required?: string[];
  properties?: Record<string, SchemaObject>;
  items?: SchemaObject;
  anyOf?: SchemaObject[];
  oneOf?: SchemaObject[];
  allOf?: SchemaObject[];
  additionalProperties?: boolean | SchemaObject;
}

const httpMethods: HttpMethod[] = [
  'get',
  'put',
  'post',
  'delete',
  'options',
  'head',
  'patch',
  'trace',
];

const defaultEngineUrl = 'http://127.0.0.1:50021';
const defaultOutputPath = 'docs/api-reference.md';

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  const engineUrl =
    options.engineUrl ?? Bun.env.VOICEVOX_ENGINE_URL ?? defaultEngineUrl;
  const outputPath = options.outputPath ?? defaultOutputPath;
  const openApi = await fetchOpenApi(engineUrl);
  const markdown = renderOpenApi(openApi, engineUrl);

  await mkdir(path.dirname(outputPath), { recursive: true });
  await Bun.write(outputPath, markdown);
}

function parseArgs(args: string[]): {
  engineUrl?: string;
  outputPath?: string;
} {
  const options: { engineUrl?: string; outputPath?: string } = {};
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    const next = args[index + 1];
    if (arg === '--engine-url' && next !== undefined) {
      options.engineUrl = next;
      index += 1;
      continue;
    }
    if (arg === '--out' && next !== undefined) {
      options.outputPath = next;
      index += 1;
      continue;
    }
    throw new Error(`Unknown or incomplete argument: ${arg}`);
  }

  return options;
}

async function fetchOpenApi(engineUrl: string): Promise<OpenApiDocument> {
  const url = new URL('/openapi.json', normalizeBaseUrl(engineUrl));
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch OpenAPI document: ${response.status}`);
  }

  const value = (await response.json()) as unknown;
  if (!isObject(value)) {
    throw new Error('OpenAPI document must be a JSON object');
  }

  return value as OpenApiDocument;
}

function normalizeBaseUrl(value: string): URL {
  const url = new URL(value);
  url.pathname = url.pathname.replace(/\/+$/u, '');
  return url;
}

function renderOpenApi(openApi: OpenApiDocument, engineUrl: string): string {
  const title = openApi.info?.title ?? 'VOICEVOX Engine';
  const version = openApi.info?.version ?? 'unknown';
  const paths = openApi.paths ?? {};
  const schemas = openApi.components?.schemas ?? {};
  const lines: string[] = [
    '# VOICEVOX Engine API Reference',
    '',
    '<!-- This file is generated by `bun run docs:api`. Do not edit it by hand. -->',
    '',
    `Source: ${title} OpenAPI ${version}`,
    `Engine URL: ${engineUrl}`,
    '',
    'This reference describes the VOICEVOX Engine HTTP API exposed by the running engine. It is not limited to the endpoints currently wrapped by vcvx-ts.',
    '',
    '## Endpoints',
    '',
  ];

  for (const [apiPath, pathItem] of Object.entries(paths)) {
    for (const method of httpMethods) {
      const operation = pathItem[method];
      if (operation === undefined) {
        continue;
      }
      lines.push(...renderOperation(apiPath, method, operation));
    }
  }

  lines.push('## Schemas', '');
  for (const [name, schema] of Object.entries(schemas)) {
    lines.push(...renderSchema(name, schema));
  }

  return `${lines.join('\n').replace(/\n{3,}/gu, '\n\n')}\n`;
}

function renderOperation(
  apiPath: string,
  method: HttpMethod,
  operation: OperationObject,
): string[] {
  const lines: string[] = [
    `### ${method.toUpperCase()} ${apiPath}`,
    '',
    `Summary: ${operation.summary ?? operation.operationId ?? 'No summary'}`,
  ];

  if (operation.tags !== undefined && operation.tags.length > 0) {
    lines.push(`Tags: ${operation.tags.join(', ')}`);
  }
  if (operation.operationId !== undefined) {
    lines.push(`Operation ID: \`${operation.operationId}\``);
  }
  if (operation.description !== undefined) {
    lines.push('', cleanDescription(operation.description));
  }

  if (operation.parameters !== undefined && operation.parameters.length > 0) {
    lines.push('', 'Parameters:', '');
    lines.push('| Name | In | Required | Schema | Description |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const parameter of operation.parameters) {
      lines.push(
        `| ${cell(parameter.name)} | ${cell(parameter.in)} | ${parameter.required === true ? 'yes' : 'no'} | ${cell(schemaLabel(parameter.schema))} | ${cell(parameter.description)} |`,
      );
    }
  }

  if (operation.requestBody !== undefined) {
    lines.push('', 'Request body:', '');
    lines.push(...renderContent(operation.requestBody.content));
  }

  if (operation.responses !== undefined) {
    lines.push('', 'Responses:', '');
    lines.push('| Status | Description | Content |');
    lines.push('| --- | --- | --- |');
    for (const [status, response] of Object.entries(operation.responses)) {
      lines.push(
        `| ${cell(status)} | ${cell(response.description)} | ${cell(contentLabel(response.content))} |`,
      );
    }
  }

  lines.push('');
  return lines;
}

function renderContent(
  content: Record<string, MediaTypeObject> | undefined,
): string[] {
  if (content === undefined || Object.keys(content).length === 0) {
    return ['No request body content.'];
  }

  const lines = ['| Content Type | Schema |', '| --- | --- |'];
  for (const [contentType, media] of Object.entries(content)) {
    lines.push(`| ${cell(contentType)} | ${cell(schemaLabel(media.schema))} |`);
  }

  return lines;
}

function renderSchema(name: string, schema: SchemaObject): string[] {
  const lines = [`### ${name}`, '', `Type: ${schemaLabel(schema)}`];
  if (schema.description !== undefined) {
    lines.push('', cleanDescription(schema.description));
  }
  if (schema.properties !== undefined) {
    const required = new Set(schema.required ?? []);
    lines.push('', '| Property | Required | Schema | Description |');
    lines.push('| --- | --- | --- | --- |');
    for (const [propertyName, property] of Object.entries(schema.properties)) {
      lines.push(
        `| ${cell(propertyName)} | ${required.has(propertyName) ? 'yes' : 'no'} | ${cell(schemaLabel(property))} | ${cell(property.description)} |`,
      );
    }
  }
  if (schema.enum !== undefined) {
    lines.push(
      '',
      `Values: ${schema.enum.map((value) => `\`${String(value)}\``).join(', ')}`,
    );
  }
  lines.push('');
  return lines;
}

function schemaLabel(schema: SchemaObject | undefined): string {
  if (schema === undefined) {
    return '';
  }
  if (schema.$ref !== undefined) {
    return refName(schema.$ref);
  }
  if (schema.anyOf !== undefined) {
    return schema.anyOf.map(schemaLabel).join(' | ');
  }
  if (schema.oneOf !== undefined) {
    return schema.oneOf.map(schemaLabel).join(' | ');
  }
  if (schema.allOf !== undefined) {
    return schema.allOf.map(schemaLabel).join(' & ');
  }
  if (schema.type === 'array') {
    return `${schemaLabel(schema.items)}[]`;
  }
  if (schema.enum !== undefined) {
    return schema.enum.map((value) => String(value)).join(' | ');
  }
  if (schema.format !== undefined && schema.type !== undefined) {
    return `${schema.type}:${schema.format}`;
  }
  if (schema.additionalProperties !== undefined && schema.type === 'object') {
    return 'object';
  }

  return schema.type ?? schema.title ?? 'unknown';
}

function contentLabel(
  content: Record<string, MediaTypeObject> | undefined,
): string {
  if (content === undefined) {
    return '';
  }

  return Object.entries(content)
    .map(
      ([contentType, media]) => `${contentType}: ${schemaLabel(media.schema)}`,
    )
    .join('<br>');
}

function refName(ref: string): string {
  return ref.split('/').at(-1) ?? ref;
}

function cleanDescription(value: string): string {
  return value.trim().replace(/\r\n?/gu, '\n');
}

function cell(value: unknown): string {
  if (value === undefined || value === null) {
    return '';
  }

  return String(value)
    .replace(/\r\n?/gu, '<br>')
    .replace(/\n/gu, '<br>')
    .replace(/\|/gu, '\\|');
}

function isObject(value: unknown): value is JsonObject {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

await main();
